// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/audit": {
            "get": {
                "description": "Returns the audit trail entries.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audit"
                ],
                "summary": "List Audit Entries",
                "responses": {
                    "200": {
                        "description": "Audit entry list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/token": {
            "post": {
                "description": "Exchanges a valid API key for a signed JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Issue Token",
                "parameters": [
                    {
                        "description": "Issue token request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.IssueTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.IssueTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/dags": {
            "get": {
                "description": "Returns all DAG configurations.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DAG"
                ],
                "summary": "List DAGs",
                "responses": {
                    "200": {
                        "description": "DAG list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new DAG configuration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DAG"
                ],
                "summary": "Create DAG",
                "parameters": [
                    {
                        "description": "DAG configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DAGConfig"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created DAG",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/dags/{id}": {
            "get": {
                "description": "Returns a DAG configuration by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DAG"
                ],
                "summary": "Get DAG",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DAG ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DAG",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing DAG configuration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DAG"
                ],
                "summary": "Update DAG",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DAG ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "DAG configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DAGConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated DAG",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a DAG configuration by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DAG"
                ],
                "summary": "Delete DAG",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DAG ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteDAGResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/dags/{id}/run": {
            "post": {
                "description": "Starts execution for a saved DAG.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "Run DAG",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DAG ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dto.RunExecutionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/episodes/{id}": {
            "get": {
                "description": "Returns a single episode by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Episodes"
                ],
                "summary": "Get Episode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Episode ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Episode",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions": {
            "get": {
                "description": "Returns executions with optional filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "List Executions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Set to summary for summary view",
                        "name": "view",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by DAG ID",
                        "name": "dag_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by execution status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (for dag_id filter)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (for dag_id filter)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Execution list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}": {
            "get": {
                "description": "Returns execution details by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "Get Execution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Execution",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/comparison-targets/{historical_id}": {
            "get": {
                "description": "Compares two executions and returns a summary.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspace"
                ],
                "summary": "Get Comparison Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Current execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Historical execution ID",
                        "name": "historical_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Comparison summary",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/episodes": {
            "get": {
                "description": "Returns all episodes for an execution; supports summary view.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Episodes"
                ],
                "summary": "List Episodes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Set to summary for summary view",
                        "name": "view",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.EpisodesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/episodes/{episode_id}/dossier": {
            "get": {
                "description": "Returns full dossier for a single episode.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspace"
                ],
                "summary": "Get Episode Dossier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Episode ID",
                        "name": "episode_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Episode dossier",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/episodes/{episode_id}/memory-recalls": {
            "get": {
                "description": "Returns memory recall items for a single episode.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspace"
                ],
                "summary": "Get Episode Memory Recalls",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Episode ID",
                        "name": "episode_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Memory recall list",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/episodes/{episode_id}/replay": {
            "get": {
                "description": "Returns replay slice view for a single episode.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspace"
                ],
                "summary": "Get Episode Replay",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Episode ID",
                        "name": "episode_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Replay percentage (0-100)",
                        "name": "percent",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Replay slice view",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/nodes": {
            "get": {
                "description": "Returns node-level results for one execution.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "Get Execution Nodes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Execution node results",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/resume": {
            "post": {
                "description": "Resumes a suspended execution.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "Resume Execution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Optional human intervention context",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.ResumeExecutionRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dto.RunExecutionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/review-actions": {
            "post": {
                "description": "Records a human review decision on an execution.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspace"
                ],
                "summary": "Post Review Action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Review action request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewActionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/review-state": {
            "get": {
                "description": "Returns aggregate human-review state for an execution.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspace"
                ],
                "summary": "Get Review State",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Review state",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/summary": {
            "get": {
                "description": "Returns a high-level summary view of one execution.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspace"
                ],
                "summary": "Get Execution Summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Execution summary",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/executions/{id}/trigger-context": {
            "get": {
                "description": "Returns trigger context view for an execution.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspace"
                ],
                "summary": "Get Trigger Context",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Trigger context",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/experiences": {
            "get": {
                "description": "Returns stored memory experiences.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Memory"
                ],
                "summary": "List Experiences",
                "responses": {
                    "200": {
                        "description": "Experience list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/run": {
            "post": {
                "description": "Accepts a full DAG configuration and executes it immediately.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "Run Inline DAG",
                "parameters": [
                    {
                        "description": "DAG configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dto.RunExecutionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/tools": {
            "get": {
                "description": "Returns all available MCP tools.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tools"
                ],
                "summary": "List Tools",
                "responses": {
                    "200": {
                        "description": "MCP tool list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIError"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service and dependency health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthResponse"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Returns process liveness status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Live Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LiveResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Returns Prometheus metrics output.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Metrics",
                "responses": {
                    "200": {
                        "description": "Prometheus metrics",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "error": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteDAGResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.EpisodesResponse": {
            "type": "object",
            "properties": {
                "episodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Episode"
                    }
                }
            }
        },
        "dto.HealthDepsResponse": {
            "type": "object",
            "properties": {
                "db": {
                    "type": "string"
                },
                "mcp": {
                    "type": "string"
                }
            }
        },
        "dto.HealthResponse": {
            "type": "object",
            "properties": {
                "deps": {
                    "$ref": "#/definitions/dto.HealthDepsResponse"
                },
                "service": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dto.IssueTokenRequest": {
            "type": "object",
            "required": [
                "api_key"
            ],
            "properties": {
                "api_key": {
                    "type": "string"
                }
            }
        },
        "dto.IssueTokenResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.LiveResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.ResumeExecutionRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "actor": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                }
            }
        },
        "dto.ReviewActionResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "dto.RunExecutionResponse": {
            "type": "object",
            "properties": {
                "execution_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.ExecutionStatus"
                }
            }
        },
        "models.ActionContext": {
            "type": "object",
            "properties": {
                "action_input": {
                    "type": "object",
                    "additionalProperties": true
                },
                "action_name": {
                    "type": "string"
                },
                "action_output": {
                    "type": "object",
                    "additionalProperties": true
                },
                "action_type": {
                    "description": "browser | api | script | mcp_tool",
                    "type": "string"
                }
            }
        },
        "models.DAGConfig": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Edge"
                    }
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Node"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Edge": {
            "type": "object",
            "properties": {
                "condition": {
                    "description": "JSON path expression for conditional routing",
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "models.Episode": {
            "type": "object",
            "properties": {
                "action_context": {
                    "description": "Type-specific context (only one of these should be non-nil).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ActionContext"
                        }
                    ]
                },
                "audit_trail": {
                    "description": "Audit / correction trail.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EpisodeAuditEntry"
                    }
                },
                "concluded_at": {
                    "description": "set when status transitions to converged/escalated",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "episode_type": {
                    "$ref": "#/definitions/models.EpisodeType"
                },
                "evidence": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EpisodeEvidence"
                    }
                },
                "exec_id": {
                    "type": "string"
                },
                "handles": {
                    "description": "Core evidence fields.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EpisodeHandle"
                    }
                },
                "human_interventions": {
                    "description": "v1 spec structured audit",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.HumanIntervention"
                    }
                },
                "id": {
                    "type": "string"
                },
                "investigation_context": {
                    "$ref": "#/definitions/models.InvestigationContext"
                },
                "loop_guard": {
                    "$ref": "#/definitions/models.EpisodeLoopGuard"
                },
                "memory_extraction": {
                    "description": "Memory extraction trigger state.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.EpisodeMemoryExtraction"
                        }
                    ]
                },
                "parent_episode_id": {
                    "description": "reserved for Sprint 11 nesting",
                    "type": "string"
                },
                "schema_version": {
                    "description": "Timestamps.",
                    "type": "integer"
                },
                "status": {
                    "description": "pending → in_progress → converged | escalated | failed",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.EpisodeStatus"
                        }
                    ]
                },
                "trigger": {
                    "description": "Trigger source (how/why the Episode was created).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.EpisodeTrigger"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                },
                "verdict": {
                    "$ref": "#/definitions/models.EpisodeVerdict"
                }
            }
        },
        "models.EpisodeAuditEntry": {
            "type": "object",
            "properties": {
                "actor": {
                    "type": "string"
                },
                "field_modified": {
                    "type": "string"
                },
                "modified_at": {
                    "type": "string"
                },
                "new_value": {},
                "node_id": {
                    "type": "string"
                },
                "old_value": {}
            }
        },
        "models.EpisodeConfidence": {
            "type": "string",
            "enum": [
                "high",
                "medium",
                "low"
            ],
            "x-enum-varnames": [
                "EpisodeConfidenceHigh",
                "EpisodeConfidenceMedium",
                "EpisodeConfidenceLow"
            ]
        },
        "models.EpisodeEvidence": {
            "type": "object",
            "properties": {
                "collected_at": {
                    "type": "string"
                },
                "collector_spec": {
                    "description": "CollectorSpec records exactly how this evidence was collected (query params,\ncommand, etc.).  Populated by Hard Nodes only; nil for Soft/Human nodes.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.EvidenceCollectorSpec"
                        }
                    ]
                },
                "content": {
                    "description": "small payloads only",
                    "type": "string"
                },
                "content_ref": {
                    "description": "\"artifact://{exec_id}/{ev_id}\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "node_type": {
                    "$ref": "#/definitions/models.NodeType"
                },
                "type": {
                    "$ref": "#/definitions/models.EpisodeEvidenceType"
                }
            }
        },
        "models.EpisodeEvidenceType": {
            "type": "string",
            "enum": [
                "fact",
                "inference",
                "human_correction"
            ],
            "x-enum-comments": {
                "EvidenceTypeFact": "written by Hard Node",
                "EvidenceTypeHumanCorrection": "written by Human Node",
                "EvidenceTypeInference": "written by Soft Node"
            },
            "x-enum-descriptions": [
                "written by Hard Node",
                "written by Soft Node",
                "written by Human Node"
            ],
            "x-enum-varnames": [
                "EvidenceTypeFact",
                "EvidenceTypeInference",
                "EvidenceTypeHumanCorrection"
            ]
        },
        "models.EpisodeHandle": {
            "type": "object",
            "properties": {
                "extracted_at": {
                    "description": "ISO 8601",
                    "type": "string"
                },
                "source": {
                    "description": "node ID that extracted this handle",
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.EpisodeHandleType"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.EpisodeHandleType": {
            "type": "string",
            "enum": [
                "request_id",
                "trace_id",
                "order_id",
                "session_id",
                "git_ref",
                "deploy_revision",
                "file_location",
                "pod_name",
                "custom"
            ],
            "x-enum-varnames": [
                "HandleTypeRequestID",
                "HandleTypeTraceID",
                "HandleTypeOrderID",
                "HandleTypeSessionID",
                "HandleTypeGitRef",
                "HandleTypeDeployRev",
                "HandleTypeFileLocation",
                "HandleTypePodName",
                "HandleTypeCustom"
            ]
        },
        "models.EpisodeLoopGuard": {
            "type": "object",
            "properties": {
                "attempted_actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "current_iteration": {
                    "type": "integer"
                },
                "max_iterations": {
                    "type": "integer"
                }
            }
        },
        "models.EpisodeMemoryExtraction": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "pending | completed | failed",
                    "type": "string"
                },
                "trigger_by": {
                    "description": "auto_high_confidence | human_confirmed",
                    "type": "string"
                },
                "triggered": {
                    "type": "boolean"
                }
            }
        },
        "models.EpisodeResult": {
            "type": "string",
            "enum": [
                "pass",
                "fail",
                "inconclusive"
            ],
            "x-enum-varnames": [
                "EpisodeResultPass",
                "EpisodeResultFail",
                "EpisodeResultInconclusive"
            ]
        },
        "models.EpisodeStatus": {
            "type": "string",
            "enum": [
                "pending",
                "in_progress",
                "converged",
                "escalated",
                "failed"
            ],
            "x-enum-varnames": [
                "EpisodeStatusPending",
                "EpisodeStatusInProgress",
                "EpisodeStatusConverged",
                "EpisodeStatusEscalated",
                "EpisodeStatusFailed"
            ]
        },
        "models.EpisodeTrigger": {
            "type": "object",
            "properties": {
                "payload": {
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "$ref": "#/definitions/models.EpisodeTriggerType"
                }
            }
        },
        "models.EpisodeTriggerType": {
            "type": "string",
            "enum": [
                "alert",
                "webhook",
                "manual",
                "scheduled"
            ],
            "x-enum-varnames": [
                "EpisodeTriggerAlert",
                "EpisodeTriggerWebhook",
                "EpisodeTriggerManual",
                "EpisodeTriggerScheduled"
            ]
        },
        "models.EpisodeType": {
            "type": "string",
            "enum": [
                "action_verification",
                "investigation_step"
            ],
            "x-enum-varnames": [
                "EpisodeTypeActionVerification",
                "EpisodeTypeInvestigationStep"
            ]
        },
        "models.EpisodeVerdict": {
            "type": "object",
            "properties": {
                "causal_chain": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "conclusion": {
                    "type": "string"
                },
                "confidence": {
                    "description": "high | medium | low",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.EpisodeConfidence"
                        }
                    ]
                },
                "decided_at": {
                    "type": "string"
                },
                "decided_by": {
                    "description": "node ID",
                    "type": "string"
                },
                "gaps": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "result": {
                    "description": "pass | fail | inconclusive",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.EpisodeResult"
                        }
                    ]
                }
            }
        },
        "models.EvidenceCollectorSpec": {
            "type": "object",
            "properties": {
                "collector_type": {
                    "description": "CollectorType classifies the collection mechanism.\nKnown values: \"script\" | \"log_query\" | \"db_query\" | \"api_call\" | \"code_search\"",
                    "type": "string"
                },
                "params": {
                    "description": "Params holds structured, human-readable query parameters.\nExamples:\n  log_query  → {\"deployment\": \"checkoutservice\", \"tail\": 120, \"keyword\": \"ORD-001\"}\n  db_query   → {\"sql\": \"SELECT * FROM cart_order WHERE order_id = 'ORD-001'\", \"db\": \"orders\"}\n  api_call   → {\"url\": \"https://…\", \"method\": \"GET\"}",
                    "type": "object",
                    "additionalProperties": true
                },
                "raw_command": {
                    "description": "RawCommand is the fully-resolved shell command for script-type collectors.\nAll {{template}} placeholders have already been substituted.",
                    "type": "string"
                }
            }
        },
        "models.ExecutionStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "completed",
                "failed",
                "timeout",
                "suspended"
            ],
            "x-enum-comments": {
                "StatusSuspended": "waiting for human approval"
            },
            "x-enum-descriptions": [
                "",
                "",
                "",
                "",
                "",
                "waiting for human approval"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusRunning",
                "StatusCompleted",
                "StatusFailed",
                "StatusTimeout",
                "StatusSuspended"
            ]
        },
        "models.HumanIntervention": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/models.HumanInterventionAction"
                },
                "actor": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.HumanInterventionAction": {
            "type": "string",
            "enum": [
                "state_override",
                "evidence_marked_invalid",
                "handle_injected",
                "hypothesis_corrected",
                "review_requested",
                "resumed",
                "aborted"
            ],
            "x-enum-comments": {
                "HumanActionSuspended": "execution paused, awaiting review"
            },
            "x-enum-descriptions": [
                "",
                "",
                "",
                "",
                "execution paused, awaiting review",
                "",
                ""
            ],
            "x-enum-varnames": [
                "HumanActionStateOverride",
                "HumanActionEvidenceMarkedInvalid",
                "HumanActionHandleInjected",
                "HumanActionHypothesisCorrected",
                "HumanActionSuspended",
                "HumanActionResumed",
                "HumanActionAborted"
            ]
        },
        "models.InvestigationContext": {
            "type": "object",
            "properties": {
                "hypothesis": {
                    "type": "string"
                },
                "known_signals": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "retrieval_plan": {
                    "type": "string"
                }
            }
        },
        "models.Node": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "bash command, LLM prompt template, MCP tool name, etc.",
                    "type": "string"
                },
                "config": {
                    "description": "additional per-type configuration",
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.NodeType"
                }
            }
        },
        "models.NodeType": {
            "type": "string",
            "enum": [
                "script",
                "llm",
                "mcp",
                "human",
                "router",
                "web_interaction"
            ],
            "x-enum-varnames": [
                "NodeTypeScript",
                "NodeTypeLLM",
                "NodeTypeMCP",
                "NodeTypeHuman",
                "NodeTypeRouter",
                "NodeTypeWebInteraction"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
